### ISSUE TITLE
Submit to MELPA?

### ISSUE THREAD

**Issue by xuchunyang** [escherdragon/sunrise-commander#29]
I know this package is already at http://joseito.republika.pl/sunrise-commander/ , but [MELPA](https://github.com/milkypostman/melpa) has the most packages and many users have already added MELPA as a ELPA repository, so submitting to MELPA will make users install this package more easily.

**Comment by escherdragon** [comment]
It used to be available via MELPA too (see issue #5 and milkypostman/melpa#153), but I've just checked out and it seems that it was removed because of some autoload cookies in the SC source code (not really sure what *exactly* the problem was, though). If you want to submit again to them you're most than welcome to do so, but please find out what changes in SC would be necessary for it to be considered "MELPA-kosher", so this effort doesn't finish like the previous one.

Cheers,
--
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by deepfire** [comment]
@escherdragon, the removal thread is:
https://github.com/melpa/melpa/pull/602
The

**Comment by deepfire** [comment]
@escherdragon, the removal thread is:
https://github.com/melpa/melpa/pull/602
The rationale for removal:
  - https://github.com/melpa/melpa/pull/602#issuecomment-15482962
  - https://github.com/melpa/melpa/pull/602#issuecomment-15484784

**Comment by eflanigan00** [comment]
I think this should really be added to MELPA
