### ISSUE TITLE
Why remotes are excluded?

### ISSUE THREAD

**Issue by vspinu** [escherdragon/sunrise-commander#30]
[I see](https://github.com/escherdragon/sunrise-commander/blob/master/sunrise-commander.el#L1903) that remotes are excluded from history. Any particular reason for that?  

My work is mostly on remotes and it's a pain to always have to navigate manually to previous directory.  

Thanks.

**Comment by escherdragon** [comment]
Hello Vitalie,

As far as I remember, the main concern with including tramp entries in the history was performance, as the code checks for the availability of the entry (i.e. whether it's accessible or not) during history navigation. Also `tramp-handle-insert-directory` does not do quite the same thing as `insert-directory` (though at the end of the day everything works fine).

In any case, a few years have passed since that code was written, and nowadays it's not that easy to even notice the performance impact of remote directories inside SC. I've made some changes and uploaded an experimental version to the following address:

[http://joseito.republika.pl/experimental/sunrise-commander.el.gz](http://joseito.republika.pl/experimental/sunrise-commander.el.gz)

why don't you give it a try and let me know what you think? The feature is optional, you'll need to activate it first by setting the `sr-history-use-tramp` variable to t (e.g. using `M-x customize-variable`).

**Comment by vspinu** [comment]
Thanks. I will test. 

By why don't you make it available through github as a branch? I am using sunrise from github anyways. It would be more convenient to test and comment.

**Comment by escherdragon** [comment]
Sure thing. Just checkout the `tramp-history` branch.

**Comment by vspinu** [comment]
I have been using the patch all this time. Everything seems to work as expected. Thanks.

The minor issues is that when VPN is disconnected and I try to go back in history tramp tries to reconnect and emacs hangs. As far as I know sunrise doesn't have anything similar to `ido-wash-history` to remove remotes from history, or does it?

**Comment by escherdragon** [comment]
On Thu, May 7, 2015 at 11:31 PM, Vitalie Spinu <notifications@github.com>
wrote:
(...)

> The minor issues is that when VPN is disconnected and I try to go back in
> history tramp tries to reconnect and emacs hangs. As far as I know sunrise
> doesn't have anything similar to ido-wash-history to remove remotes from
> history, or does it?
>
(...)

No, not yet. Actually I was planning to write one and tie it to the
customization function of the `sr-history-use-tramp', but probably having
it as a standalone command has actually more merit -- something like the
following:

(defun sr-history-purge-remote()
>   "Remove all remote entries from the history of directories."
>   (interactive)
>   (mapc
>    (lambda (side)
>      (let ((pane (assoc side sr-history-registry)))
>        (setcdr pane (remove-if (lambda (x) (string-match
> tramp-file-name-regexp x)) (cdr pane)))))
>    '(left right)))
>

Cheers,
-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by escherdragon** [comment]
Hi Vitalie,

I've been thinking a lot lately about this solution (I'm surprised myself of all the ramifications this simple modification is turning out to have). In particular it bothers me that the inclusion of remote directories makes the history mechanism unreliable, as you never know how long you'll need to wait for the list of directories to show, or whether it will work at all (like e.g. when the connection is down). Besides, it doesn't really work in older versions of emacs (22 and old 23 ones - I'm still fixing problems there). I've made some tweaks to the previous solution (see 7d59ef178): with these changes SC won't show any attributes of the remote directories, but in exchange it will display the list as fast as always, and the mechanism is guaranteed not to hang or crash even without an internet connection available. It'd even make the `sr-history-use-tramp' switch superfluous. Can you please give this new version a try and let me know how do you like it?

Cheers,

José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by vspinu** [comment]
Sure. I have re-fetch the branch. Will see how it goes. 

>  with these changes SC won't show any attributes of the remote directories, but in exchange it will display the list as fast as always, and the mechanism is guaranteed not to hang or crash even without an internet connection available

Do attributes include time change and size? There will still be a way to see those, right?

**Comment by escherdragon** [comment]
On Sun, May 10, 2015 at 12:29 PM, Vitalie Spinu <notifications@github.com>
wrote:
(...)

> Do attributes include time change and size? There will still be a way to
> see those, right?
>
(...)

Real sizes of directories are not displayed by default even for local
entries anyway (there isn't yet a facility like the one in Total Commander
to calculate on demand and display the sizes of the directories in the
current pane), but you can press y (sr-show-files-info)  to get the size of
any particular entry, either local or remote. Dates instead may be a
problem indeed, but they already depend on the tramp back-end in use, for
instance FTP entries don't get anything other than "1970-01-01". It's not
that bad for SSH, but I'd expect this behavior to be highly inconsistent
across the other back-ends. Would this be a deal breaker for you?

Cheers,
-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by vspinu** [comment]
>>> José Alfredo Romero L. on Sun, 10 May 2015 04:21:18 -0700 wrote:
> Would this be a deal breaker for you?

Not at all if sorting on time still represents the actual order. And I
think it does.

**Comment by escherdragon** [comment]
On Mon, May 11, 2015 at 12:35 AM, Vitalie Spinu <notifications@github.com>
wrote:

> >>> José Alfredo Romero L. on Sun, 10 May 2015 04:21:18 -0700 wrote:
> > Would this be a deal breaker for you?
>
> Not at all if sorting on time still represents the actual order. And I
> think it does.
>
(...)

Insertion order? Yes, it is and will always be respected, otherwise the
name "history of recently visited directories" would not really apply ;-)

Very well, in that case I think I'll just ditch the `sr-history-use-tramp'
flag (so the feature is always on), merge the result into master as a new
release and close the issue (today evening, probably). Thank you very much
for your help, Vitalie.

Cheers,
-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by vspinu** [comment]
Thanks a lot for this. It works nicely.
